name: Run PR Tests
on:
  pull_request:
    branches: [ main ] # Triggers on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22.19.0'
    - run: npm i
    - run: npm run lint
    - run: npm run test
